### ISSUE TITLE
ProcessWire namespace

### ISSUE THREAD

**Issue by ryancramerdesign** [horst-n/WireMailSmtp#13]
Hi @horst-n I was wondering if at some point in the future (no rush) you'd consider adding a `namespace ProcessWire;` to this module's PHP/module files so that PW doesn't have to compile it? I understand you've got several 3rd party classes that are in the root namespace and may need to remain so, so any references to them would need to be changed to have a backslash in front of them, like this:
~~~~~
$this->emailMessage = new \smtp_message_class();
~~~~~

**Comment by horst-n** [comment]
Hi @ryancramerdesign , I know that there are active installations under PW versions 2.4.x and 2.5.x that uses it. I don't want to break something in this versions. As far as I remember right, there is much lower support for version checking or disallow installation on mismatching requirements in that older PW versions.
Maybe you can give me some hint on how I can stay within this repo and update to PW 3.0.x?
Should I create a separate branch for PW versions up to 2.7.x? But whats best to secure that people cannot install a new 3.x version into lower systems by using one of the different update features?
