### ISSUE TITLE
PHP 7.4 deprecated warning in email_message.php

### ISSUE THREAD

**Issue by esszett** [horst-n/WireMailSmtp#14]
…is it safe to just remove this part of the condition?

`1×	
PHP Deprecated: Function get_magic_quotes_runtime() is deprecated in .../smtp_classes/email_message.php:907
`

`if((GetType($size)=="integer"&& strlen($body)>$size)
					|| (function_exists("get_magic_quotes_runtime")
					&& get_magic_quotes_runtime()))
						$body=StripSlashes($body);`

**Comment by szabeszg** [comment]
Hello Horst,

Any chance you fix this?

**Comment by horst-n** [comment]
@szabeszg As far as I understand, Deprecation warnings are hints to developers when error level is set to E_ALL or likely. But this is nothing you use in production. Also I do not get this with PHP 7.4+ on my local dev machine. ??
