### ISSUE TITLE
Fatal error on latest version with php 8.2

### ISSUE THREAD

**Issue by marloren** [horst-n/WireMailSmtp#19]
Hi there, 

I've just installed this awesome plugin that I'm using on pretty much all of my sites. But when testing whether the SMTP connection works, I'm getting the following error:

"Fatal Error: Uncaught Error: Class "WireMailSmtp" not found in site/modules/WireMailSmtp/WireMailSmtpAdaptor.php:143"

I'm using PW's latest dev version.

**Comment by tbba** [comment]
PGP 8.1 as well. Probably not PHP related but due to PW changes?
