### ISSUE TITLE
Multiple CC only sending to To and last CC

### ISSUE THREAD

**Issue by Notanotherdotcom** [horst-n/WireMailSmtp#3]
As the title says, there's an issue with CC - no matter which way you do the CC's (array of email addresses, associative array of email addresses and names) only the last person in the CC and the person in the To ever gets the email.

I was testing this with 3 recipients and the first CC was skipped over for some reason.

**Comment by Notanotherdotcom** [comment]
And I do wish a lot of your additions were in the other email classes too - I'm having fun with yours, I just like consistency too :)

**Comment by horst-n** [comment]
Hi @Notanotherdotcom 
Do you remember if you have used it with the setting "single" => true?

**Comment by horst-n** [comment]
It seems to be fixed now with the commit 30 minutes ago.
