### ISSUE TITLE
no authentication required

### ISSUE THREAD

**Issue by mackski** [horst-n/WireMailSmtp#4]
Maybe an edge case, but when my SMTP server does not require authentication, the module test fails.
This is actually a false positive, even though the module test fails, the module still sends email as expected.
The offending code is part of the smtp.php library:

```
if($success
&& strlen($mechanism)==0)
{ 
$this->error="it is not supported any of the authentication mechanisms required by the server";    
$success=0;
}
```

**Comment by horst-n** [comment]
will fix it

**Comment by fellu** [comment]
Hiya, any timetable for this fix? :)

**Comment by xnikox** [comment]
Any news? :-)

**Comment by horst-n** [comment]
@xnikox please try this branch and report back if it works on your side:
https://github.com/horst-n/WireMailSmtp/tree/allow_without_authentication
