### ISSUE TITLE
Date issue WireMailSmtpAdaptor.php

### ISSUE THREAD

**Issue by selsermedia** [horst-n/WireMailSmtp#5]
There is a string formatting error on date string set on line 350 in WireMailSmtpAdapter.php

`$this->emailMessage->SetHeader("Date", gmdate("D, j M Y H:i:s \G\M\T P"));`

Systems strictly observing RFC2822, will not accept the addition of the (Difference to Greenwich time (GMT) with colon between hours and minutes )added to the end date string created. 

This causes issues with systems like Amazon AWS SES, Rackspace Mailgun, among others. 

Line 350 should be changed to. 

 `$this->emailMessage->SetHeader("Date", gmdate("D, j M Y H:i:s \G\M\T"));`

 https://www.ietf.org/rfc/rfc2822.txt

Credit goes to Rackspace tech support for isolating this.

**Comment by horst-n** [comment]
fixed it! Many thanks for contributing / sharing!
